
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FOR ID IGUAL INT LLAVEA LLAVEC MASMAS MENOR_IGUAL NUMBER OUT PA PC PLUS POT PRINTLN PUNTO_COMA STRING SYSTEMexpresion : FOR PA INT ID IGUAL NUMBER PUNTO_COMA ID MENOR_IGUAL NUMBER PUNTO_COMA ID MASMAS PC LLAVEA SYSTEM POT OUT POT PRINTLN PA STRING PLUS NUMBER PC PUNTO_COMA LLAVEC'
    
_lr_action_items = {'FOR':([0,],[2,]),'$end':([1,28,],[0,-1,]),'PA':([2,21,],[3,22,]),'INT':([3,],[4,]),'ID':([4,8,12,],[5,9,13,]),'IGUAL':([5,],[6,]),'NUMBER':([6,10,24,],[7,11,25,]),'PUNTO_COMA':([7,11,26,],[8,12,27,]),'MENOR_IGUAL':([9,],[10,]),'MASMAS':([13,],[14,]),'PC':([14,25,],[15,26,]),'LLAVEA':([15,],[16,]),'SYSTEM':([16,],[17,]),'POT':([17,19,],[18,20,]),'OUT':([18,],[19,]),'PRINTLN':([20,],[21,]),'STRING':([22,],[23,]),'PLUS':([23,],[24,]),'LLAVEC':([27,],[28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> FOR PA INT ID IGUAL NUMBER PUNTO_COMA ID MENOR_IGUAL NUMBER PUNTO_COMA ID MASMAS PC LLAVEA SYSTEM POT OUT POT PRINTLN PA STRING PLUS NUMBER PC PUNTO_COMA LLAVEC','expresion',27,'p_statement_for_loop','ejemplo.py',130),
]
